### PR TITLE
Frontend team adding things to the website

### PR DESCRIPTION
**Pull request by SneK152**

### CODE REVIEW

**Comment by wonksknow-oliver** [comment]
In future, make sure you use descriptive commit messages that explain what was done in that commit.

**Comment by SneK152** [comment]
Sure, I'll provide more details in the future.

**Comment by SneK152** [comment]
The branch merges that just happened was me updating the fork I made to the new changes in this repository.

**Comment by NeilP483** [comment]
Can you move the first route back to it's initial position and delete the new if name == main clause

**Pull request merged**
